# Generated by Django 4.2.7 on 2023-11-09 14:57

import algo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating')),
                ('image', models.ImageField(default='br_pic/image.jpg', upload_to=algo.models.image_path, verbose_name='Photo')),
                ('facebook_page_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Facebook Page ID')),
                ('is_beach', models.BooleanField(default=False, verbose_name='Is Beach')),
                ('is_resort', models.BooleanField(default=False, verbose_name='Is Resort')),
                ('place_identifier', models.CharField(max_length=10, unique=True, verbose_name='Place Identifier')),
            ],
        ),
    ]
