# Generated by Django 4.2.7 on 2023-11-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_identifier',
            field=models.CharField(max_length=25, unique=True, verbose_name='Place Identifier'),
        ),
    ]
