# Generated by Django 4.2.7 on 2023-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_alter_place_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='keywords',
            field=models.CharField(default='', max_length=300, verbose_name='Keywords'),
        ),
    ]
